protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	public function actionWoo(){
	  echo '<link rel="stylesheet/less" type="text/css" href="'.Yii::app()->request->baseUrl.'/css/main.less">
	<script type="text/javascript" src="'.Yii::app()->request->baseUrl.'/js/less-1.3.0.min.js"></script>';
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
	  $model = new Post;
	  $c = new CDbCriteria();
	  $c->condition = 'news_id > 0';
	  $c->order = 'news_id desc';
	  
	  $count=News::model()->count($c);
	  
	  $pages=new CPagination($count);
	  $pages->pageSize=5;
	  $pages->applyLimit($c);

	  $posts=News::model()->findAll($c);
    /* 
     * Posts per page
     */
	  $pages->pageSize=10;
	  $pages->applyLimit($c);
	  $posts=News::model()->findAll($c);
	  /*print_r(Yii::app()->user->mod_branches);*/
	  $this->render('index',array('model'=>$model,'posts'=>$posts, 'pages' => $pages));
		  }
	
	
	
	public function actionAjaxtags(){
	  $q = $_GET['q'];
	  
	  $posts = Yii::app()->db->createCommand();
	  $posts->select('tag');
	  $posts->from('image_tags');
	  $keyword=strtr($q, array('%'=>'\%', '_'=>'\_'));
	  $posts->where(array('like','tag','%'.$keyword.'%'));
	  $tags = $posts->queryAll();
	  //print_r($tags);
	   $tarray=array();
	  foreach($tags as $row){
	      $tarray[] = $row['tag'];
	  }
	  $tarray = array_unique($tarray);
	  
	  $s='';
	  $i=0;
	  foreach($tarray as $k=>$v){
	     $i++;
	    if($i !== count($tarray))
	      $s .= '"'.$v.'", ';
	    if($i == count($tarray))
	      $s .= '"'.$v.'"'; 
	   
	  }
	  header('Content-type: application/json');
	  echo '['.$s.']';
	}
	public function actionShow(){
	  print_r($_POST);
	}
	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
	    if($error=Yii::app()->errorHandler->error)
	    {
	    	if(Yii::app()->request->isAjaxRequest)
	    		echo $error['message'];
	    	else
	        	$this->render('error', $error);
	    }
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$headers="From: {$model->email}\r\nReply-To: {$model->email}";
				mail(Yii::app()->params['adminEmail'],$model->subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate()){
			  $mod = new Iplog;
			  $mod->ip = $_SERVER['REMOTE_ADDR'];
			  $mod->user_id = Yii::app()->user->id;
			  $mod->save();
			  $this->redirect(Yii::app()->user->returnUrl);
			}
		}
		// display the login form
		
		$this->render('login',array('model'=>$model));
	}

	public $id;
	public function actionProfile(){
	  $model = new Profile;
	  $id=Yii::app()->getRequest()->getQuery('id');
	  $this->id=$id;
	  $exists=Profile::model()->exists('profile_id =:id',array(':id' => $id));
	  $user_exists=User::model()->exists('id =:id',array(':id' => $id));
	  if($exists and $user_exists){
	    $models = Profile::model()->findAll(array(
						      'condition' => 'profile_id = :id',
						      'params' => array(':id' => $id),
						      ));
	    $user_models = User::model()->findAll(array(
						      'condition' => 'id = :id',
						      'params' => array(':id' => $id),
						      ));	    
	    $user = array();
	    
	    foreach($models as $m){
	      $user['aboutme'] = $m->aboutme;
	      $user['website'] = $m->website;
	      $user['privacy'] = $m->privacy;
	    }
	    foreach($user_models as $a){
	      $user['join'] = $a->join;
	      $user['birthday'] = $a->dob;
	      $user['username'] = $a->username;
	      $user['email'] = $a->email;
	      $user['id'] = $id;
	    }

	    /* $m2 array */

	   $m2= Yii::app()->db->createCommand()
	     ->select('*')
	     ->from('tbl_contacts')
	     ->join('tbl_profile', 'tbl_contacts.contact = tbl_profile.profile_id')
	     ->join('tbl_user', 'tbl_contacts.contact = tbl_user.id')
	     ->where('owner=:id', array(':id'=>$id))
	     ->queryAll();
	  
	   if(!Yii::app()->user->isGuest){
	    
	   $m3= Yii::app()->db->createCommand()
	     ->select('*')
	     ->from('tbl_contacts')
	     ->join('tbl_profile', 'tbl_contacts.contact = tbl_profile.profile_id')
	     ->join('tbl_user', 'tbl_contacts.contact = tbl_user.id')
	     ->where('owner=:id', array(':id'=>Yii::app()->user->id))
	     ->queryAll();
	   } else {
	     $m3 = array();
	   }
	   $logins = Iplog::model()->findAll(array(
						   'condition' => 'user_id = :id',
						   'params' => array(':id' => $id),
						   'order' => 'time desc',
						   'limit' => '1'
						   ));
	   foreach($logins as $row){
	     $last_login = strtotime($row->time);	     
	   }
	   if(@!$last_login) $last_login = 0;
	    $this->pageTitle=$user['username'].' / '.Yii::app()->name;
	    $this->render('view_profile', array('user' => $user, 'contacts' => $m2, 'viewer_contacts' => $m3, 'last_login' => $last_login));
	  }
	  elseif($user_exists and !$exists){
	    Yii::app()->user->setFlash('error', "This user has no profile.");
	    $this->render('usr_error');
	      }
	  elseif(!$user_exists){
	    Yii::app()->user->setFlash('error', "Sorry, this user doesn't exist.");
	    $this->render('usr_error');
	  }
	}

	public function actionAddc(){
	  $id = $_GET['c'];
	  if(!isset($_POST['confirm'])){
	      $this->render('confirmadd', array('id'=>$id));
	    } else {
	      if($_POST['confirm']['sure'] == 1){
		if(!Yii::app()->user->isGuest){
		  
		  if($id != Yii::app()->user->id){
		    $m3= Yii::app()->db->createCommand()
		      ->select('*')
		      ->from('tbl_profile')
		      ->where('profile_id=:id', array(':id'=>$id))
		      ->queryRow();
		    
		    $m4= Yii::app()->db->createCommand() //return true if the user is already a contact
		      ->select('*')
		      ->from('tbl_contacts')
		      ->where('owner=:id and contact=:id2', array(':id'=>Yii::app()->user->id, 'id2' => $id))
		      ->queryAll();
		    
		    if(count($m4) == 0){
		      if($m3['profile_id']>0){
			$model = new Contacts;
			$model->owner = Yii::app()->user->id;
			$model->contact = $id;
			$model->save();
			$this->redirect('/testdrive/site/profile/'.$id);
		      } else 
			throw new CHttpException(404,'The specified user could not be found.');
		    } else 
		      throw new CHttpException(404,'This user is already in your contacts list.');
		  } else
		    throw new CHttpException(404,'You can not add yourself to your contacts.');
		} else 
		  throw new CHttpException(404,'Plese log in to add contacts.');	
	      } else {
		$this->redirect('/testdrive');
	    }
	    }
	}

	public function actionDelc(){
	  $id=$_GET['id'];
	  if(!isset($_POST['confirm'])){
	      $this->render('confirmdel', array('id'=>$id));
	    } else {
	      if($_POST['confirm']['sure'] == 1){
	  $m4= Yii::app()->db->createCommand() //return true if the user is already a contact
	    ->select('*')
	    ->from('tbl_contacts')
	    ->where('owner=:id and contact=:id2', array(':id'=>Yii::app()->user->id, 'id2' => $id))
	    ->queryAll();
	  
	  if(count($m4) > 0){
	    if(!Yii::app()->user->isGuest){
	      Contacts::model()->deleteAll(array(
					     'condition' => 'contact = :id and owner = :id2',
					     'params' => array(':id' => $id, 'id2' => Yii::app()->user->id),
					     ));
	      $this->redirect('/testdrive/site/profile/'.Yii::app()->user->id);
	    } else {
	      throw new CHttpException(404,'Plese log in to remove contacts.');
	    }
	  } else {
	    throw new CHttpException(404,'The specified user could not be found.');
	  }
	      } else
		$this->redirect('/testdrive/profile/'.Yii::app()->user->id);
	  }
	}
	
	public function actionSettings(){
	  $model=new Profile;
	  if(!Yii::app()->user->isGuest){
	    $id = Yii::app()->user->id;
	    $exists=Profile::model()->exists('profile_id =:id',array(':id' => $id));
	    $models = Profile::model()->findAll(array(
						      'condition' => 'profile_id = :id',
						      'params' => array(':id' => $id),
						      ));
	    $logins = Iplog::model()->findAll(array(
						      'condition' => 'user_id = :id',
						      'params' => array(':id' => $id),
						      ));
	    $user=array();
	    if(!$exists){
	      $user['aboutme'] = '';
	      $user['website'] = '';
	      $user['privacy'] = 1;
	      $user['css'] = '';
	    } else {
	      foreach($models as $m){
		$user['aboutme'] = $m->aboutme;
		$user['website'] = $m->website;
		$user['privacy'] = $m->privacy;
		$user['css'] = $m->css;
	      }     
	    }
	    
	    if(isset($_POST['Settings'])){
	      $a=0;
	      $model->attributes = $_POST['Settings'];
	      $model->profile_id = $id;
	      if($model->validate()){
		if($exists){
		  $w=Profile::model()->findByPk($id);
		  $w->aboutme = $_POST['Settings']['aboutme'];
		  $w->website = $_POST['Settings']['website'];

protected/views/layouts/column1.php
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <title><?php echo CHtml::encode($this->pageTitle); ?></title>
      <meta name="description" content="">
	<meta name="viewport" content="width=device-width">
	  <script>
	  function show_fulldate(newdate, id) {
	  nid = '#'+id;
	  $(nid).fadeOut(function() {
	  $(this).text(newdate).fadeIn('fast');
	  });
	  }
	  $('a').click(function showLogin(){
	  $('#slidein_login').toggle('slide',300);
	  });   
	</script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/Markdown.Converter.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/Markdown.Sanitizer.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/Markdown.Editor.js"></script>
	<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css">
	<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/style.css">
	
	<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl;?>/site/Usrstyle?id=<?=$this->id;?>">
	
	
	
	<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/md.css">
	<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/libs/modernizr-2.5.3.min.js"></script>
	<link rel="stylesheet/less" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/test.less">
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/less-1.3.0.min.js"></script>
      </head>
      <body>
	<!--[if lt IE 7]>
	    <p>The browser you are using is nearly <em>12 years old</em>. 
	    That's like 50 years in Internet time. Please upgrade to a better browser! 
	    <a href="http://browsehappy.com">Go to browsehappy.com to learn how!</a></p>
	    <![endif]-->
	<header>
	  <div class="container">
	    <div class="row">
	      <div class="twelvecol" id="title_bar">
		<img src="/testdrive/css/stacker_main.png" alt="Stacker" />
		
		
		<div id="menu-top">
		  <?php $this->widget('zii.widgets.CMenu',array( 
		    'itemCssClass' => 'top_list_item', 'firstItemCssClass' =>
		    'first', 'activeCssClass' => 'active_menu',
		    'linkLabelWrapper' => 'span',
		    'items'=>array(
		    array('label'=>'Home', 'url'=>array('/site/index'),
  		    ),
		    array('label'=>'Forums','url'=>array('/forum')),
		    array('label'=>'Settings', 'url'=>array('/site/settings'), 'visible'=>!Yii::app()->user->isGuest),
		    array('label'=>'Login', 'url'=>array('/site/login'),
		    'visible'=>Yii::app()->user->isGuest, 'linkOptions' =>
		    array('id' => 'login_activate')),
		    array('label'=>'Me', 'url'=>array('/profile/'.Yii::app()->user->id), 'visible'=>!Yii::app()->user->isGuest),
		    array('label'=>'Join', 'url'=>array('/site/newusr'), 'visible'=>Yii::app()->user->isGuest),
		    array('label'=>'Logout('.Yii::app()->user->name.')','url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest),
		    ),
		    ));
		  ?>
		</div>
	      </div>
	    </div>
	  </div>
	</header>
	<div class="container mpart">
	  <div class="row">
	    <div class="onecol">
	    </div>
	    
	    <div class="tencol last">
	      <div class="row">
		
		<?php echo $content; ?>
		
	      </div>
	    </div>
	    <div class="onecol">
	    </div>
	  </div>
	</div>
	
	
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/md.css" />
	
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="<?php echo Yii::app()->request->baseUrl; ?>js/libs/jquery-1.7.1.min.js"><\/script>')</script>
	
	<!-- scripts concatenated and minified via build script -->
	<script src="<?php echo Yii::app()->request->baseUrl; ?>js/plugins.js"></script>
	<script src="<?php echo Yii::app()->request->baseUrl; ?>js/script.js"></script>
	<!-- end scripts -->
	
	<!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
	     mathiasbynens.be/notes/async-analytics-snippet -->
	<script>
	  var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
	  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
	  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
	  s.parentNode.insertBefore(g,s)}(document,'script'));
	</script>
	<script type="text/javascript">
	  (function () {
	  var converter1 = Markdown.getSanitizingConverter();
	  var editor1 = new Markdown.Editor(converter1);
	  editor1.run();
	  
	  var converter2 = new Markdown.Converter();
	  
	  converter2.hooks.chain("preConversion", function (text) {
	  return text.replace(/\b(a\w*)/gi, "*$1*");
	  });
	  
	  converter2.hooks.chain("plainLinkText", function (url) {
	  return "This is a link to " + url.replace(/^https?:\/\//, "");
	  });
	  
	  var help = function () { alert("Do you need help?"); }
	  
	  var editor2 = new Markdown.Editor(converter2, "-second", { handler: help });
	  
	  editor2.run();
	  })();
        </script>
	
      </body>
    </html>
    
    